### ISSUE TITLE
Markup

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#11]
Hey guys,
If you could both push whatever you have marked up to the repo, that'd be be great! Even if they aren't up-to-date with the current schema, push your files anyways. They can always be updated later, but at least they will be here! Thanks!

**Comment by alnopa9** [comment]
Just wanted to push a reminder on this issue! I know Dr. B mentioned it after class today, but **please** push your work onto the repo. We don't want to get too far behind in markup! We should have a total of 69 works marked up by the end of this week and we are not even close to that number.
@James-f117 @abdual1100

**Comment by James-f117** [comment]
Hey Alyssa where are we pushing the picture to?

**Comment by James-f117** [comment]
Also is there any website that you can obtain the dimensions of the piece none of the articles I just did gave any information of the size of the piece and when googled I couldn't find anything out.

**Comment by James-f117** [comment]
One more thing, I accidentally saved one of my XML's as the layout XML so I copied the layout, re-resaved it, and had to push it because I don't know how to fix it in git bash once that happens.

**Comment by alnopa9** [comment]
@James-f117 Hey, James! Sorry, I just got home from work! But I have the size element as optional in the schema, and I've been having a hard time finding exact measurements for mine as well. I'm thinking of removing it or changing the acceptable values to something like small, medium, or large. 
The pictures now go in the tags folder, the file path is Banksy>pages>img>tags.
Thanks for fixing the layout! Whenever I save over a file, I just get the last version that I want off the repo and save it again, which sounds like what you did.

**Comment by James-f117** [comment]
Alright thanks! If you want to remove it let me know i'm updating the XML to include the medium element and the alt attribute so I can just go ahead and delete the size element and push that up
