### ISSUE TITLE
Project Checkpoint 3 (due F 2/15)

### ISSUE THREAD

**Issue by ebeshero** [alnopa9/Banksy#15]
@alnopa9 @abdual1100 @James-f117 For Project Checkpoint 3, this team already has an amazing web presence, but it needs MUCH more work behind the scenes. I expect that @abdual1100 and @James-f117 will put in most of the work for this checkpoint because the Banksy team needs XML markup and schema work.

**Comment by ebeshero** [comment]
Just a quick comment to congratulate Bansky Team for pulling together to complete Project Checkpoint 3! Your contributor graph on this repo shows much more life now, and Banksy is producing some great project markup at this point. @alnopa9 has been doing amazing things with the website, while @James-f117 and @abdual1100 are working steadily now on the markup. 
https://github.com/alnopa9/Banksy/graphs/contributors

Going forward, the team may want to be practicing a bit with Banksy markup in XQuery to practice pulling some data from it. (We're likely to make that a homework exercise soon, anyway!) Think about what kinds of information your markup is making available for looking at patterns in Banksy's work. Just to keep on keeping on, make sure each of you continues with regular time every week for project work, and that includes *thinking* about what your work and exploring it--seeing what you can find out from your markup. Posting on your GitHub repo is a good way to make sure everyone sees them and you don't forget a sudden neat idea you just had. :-) Keep up the good work!

**Comment by alnopa9** [comment]
@James-f117 @abdual1100 Keep up the great work, guys!! 👍
