### ISSUE TITLE
Fixing the Repo

### ISSUE THREAD

**Issue by James-f117** [alnopa9/Banksy#16]
@alnopa9 @abdual1100 
Hey Alyssa were you able to figure out the issue we were having with the repo or has anyone from GitHub contacted you?

**Comment by ebeshero** [comment]
@James-f117 I think @alnopa9 may have fixed it by reorganizing the repo without the KML directory. Try a `git pull` on the repo now...what happens?

**Comment by James-f117** [comment]
Okay I forked the repo and cloned that one and it worked. So then I deleted the one for the original from my computer and recloned it and now everything seems fine

**Comment by alnopa9** [comment]
Okay! I think that means our repo is up and running again! 🎉

**Comment by ebeshero** [comment]
Okay--so the GitHub developers are still mystified about what happened, but I talked to @djbpitt about it (my friend who teaches the Pitt DH class), and he cloned your repo and had a look. He spotted something we were seeing on @James-f117's monitor today: that the `KML` directory had a white space at the end of its name, like this: `KML `. We could see that on the PC computer, but it wasn't so easy to see on my Mac or on @abdual1100's Mac. @djbpitt used a tree program to look at the directory structure at the time of the problematic directory, and here's what it looked like:

![image](https://user-images.githubusercontent.com/4014518/52895016-24895400-3182-11e9-9e2f-27a05b8628a3.png)

See that white space? 
So, we learned the hard way that PC's can't tolerate white spaces at the ends of file directory names in GitHub--and they *really* can't tolerate them! So when @alnopa9 got rid of the file directory and saved the documents in a new KML file, that fixed the problem. But you could probably also try re-creating that KML directory again without any white spaces this time.
