### ISSUE TITLE
Team Meetings

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#2]
Please post times that you would be able to attend group meetings!
MWF- anytime after 3
Tuesday and Thursday- anytime after 2:30
I work this Friday at 2:30, so we wouldn't be able to have a meeting that day.

**Comment by James-f117** [comment]
MWF after 3 is good for me

**Comment by abdual1100** [comment]
Monday works for me

**Comment by alnopa9** [comment]
Mondays at 3 for our weekly team meetings, then! Does meeting in the library work for everyone, too?

**Comment by abdual1100** [comment]
Yes, the library works for me
3 PM is good for me
Thanks

**Comment by James-f117** [comment]
The library is good for me as well!

**Comment by alnopa9** [comment]
Okay! I'm going to close this issue. See everyone in class on Friday! 👍
