### ISSUE TITLE
Today's Meeting (2/18/19)

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#20]
Just posting a reminder about today's meeting at 3! Instead of the library, would it work to just meet in room FOB 131? Hope to see you guys there!
@James-f117 @abdual1100

**Comment by alnopa9** [comment]
We can go over XPath some more in the meeting, too!

**Comment by James-f117** [comment]
Yeah I’m fine with meeting in the office!

**Comment by abdual1100** [comment]
Yeah, Im good with meeting up at room 131. See you then!

**Comment by alnopa9** [comment]
Alright! I'll see you guys soon!
