### ISSUE TITLE
Completed Markup

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#22]
### The objective for this issue is to keep track of the works we have completed markup for, links to the XML document, lines for corresponding KML markup in [map.kml](https://github.com/alnopa9/Banksy/blob/master/data/map.kml), and the person who made the markup.
* [Girl With Balloon](https://github.com/alnopa9/Banksy/blob/master/data/XML/girl_with_balloon.xml) Lines 4-13 - Alyssa
* [Sweep It Under The Carpet](https://github.com/alnopa9/Banksy/blob/master/data/XML/Sweep_Under_Rug.xml) Lines 14-23 - Abdual
* [Snorting Copper](https://github.com/alnopa9/Banksy/blob/master/data/XML/Snorting_Copper_Banksy.xml) Lines 24-33 - Abdual
* [Shave Kong](https://github.com/alnopa9/Banksy/blob/master/data/XML/Shave_Kong.xml) Lines 34-43 - Abdual
* [Well, Hung Lover](https://github.com/alnopa9/Banksy/blob/master/data/XML/Man_Hanging_Banksy.xml) Lines 44-53 - Abdual
* [Graffiti is a Crime](https://github.com/alnopa9/Banksy/blob/master/data/XML/Graffiti_Crime.xml) Lines 54-63 - Abdual
* [Bomb Hugger](https://github.com/alnopa9/Banksy/blob/master/data/XML/Bomb_Hugger.xml) Lines  64-73 - Abdual
* [Cash Machine Girl](https://github.com/alnopa9/Banksy/blob/master/data/XML/Cash_Machine_Girl.xml) Lines 74-83 - Abdual
* [Child Soldier](https://github.com/alnopa9/Banksy/blob/master/data/XML/Child_Soldier.xml) Lines 84-93 - Abdual
* [Follow Your Dreams](https://github.com/alnopa9/Banksy/blob/master/data/XML/Follow_Dreams.xml) Lines 94-103 - Abdual
* [Gangsta Rat](https://github.com/alnopa9/Banksy/blob/master/data/XML/Gansta_Rat.xml) Lines 104-113 - Abdual
* [I Want Change](https://github.com/alnopa9/Banksy/blob/master/data/XML/i_want_change.xml) Lines 114-123 - James
* [Seal Mural](https://github.com/alnopa9/Banksy/blob/master/data/XML/seal.xml) Lines 124-133 - James
* [Blinded Napoleon](https://github.com/alnopa9/Banksy/blob/master/data/XML/blinded_napoleon.xml) Lines 134-143 - James
* [Box Cutter Rat](https://github.com/alnopa9/Banksy/blob/master/data/XML/boxcutter_rat.xml) Lines 144-153 - James
* [Bronx Zoo](https://github.com/alnopa9/Banksy/blob/master/data/XML/bronx_zoo.xml) Lines 154-163 - James
* [Go Flock Yourself](https://github.com/alnopa9/Banksy/blob/master/data/XML/go_flock_yourself.xml) Lines 164-173 - James
* [Choose Your Weapon](https://github.com/alnopa9/Banksy/blob/master/data/XML/haring_dog.xml) Lines 174-183 - Alyssa
* [Mild Mild West](https://github.com/alnopa9/Banksy/blob/master/data/XML/mild_mild_west.xml) Lines 184-193 - Alyssa
* [Pillow Fight](https://github.com/alnopa9/Banksy/blob/master/data/XML/pillow_fight.xml) Lines 194-203 - James
* [Season's Greetings](https://github.com/alnopa9/Banksy/blob/master/data/XML/seasons_greetings.xml) Lines 204-213 - Alyssa
* [Security Guard With Pink Balloon](https://github.com/alnopa9/Banksy/blob/master/data/XML/Security_Pink_Balloon.xml) Lines 214-223 - Abdual
* [Hammer Boy](https://github.com/alnopa9/Banksy/blob/master/data/XML/Hammer_Boy.xml) Lines 224-233- Abdual
* [Injured Buddha](https://github.com/alnopa9/Banksy/blob/master/data/XML/Injured_Buddha.xml) Lines 234-243 - Abdual

**Comment by abdual1100** [comment]
Hammer Boy - Abdual
Injured Buddha - Abdual

**Comment by ebeshero** [comment]
Wow--this is super helpful! I wanted to point out the checklist in Markdown for posts like this one: When you open a comment here, there's a little icon with a checkmark and a few lines (right next to the numbered list icon). Try it out: 

- [ ] Checklist activity
- [ ] Checklist activity

You can create a list and have people check it off as they go. This can be very satisfying during a coding sprint! @alnopa9 @abdual1100 @James-f117

**Comment by alnopa9** [comment]
@ebeshero I thought about making this into a checklist but that would require a list of tags we have yet to do. The team is gathering info on each tag as we go. This is just here to keep track of markup and make sure we don't write up the same tag twice. And I agree, nothing is more satisfying than checking off something in a checklist. I used them a lot in the Combe project's Issues last semester!
