### ISSUE TITLE
Banksy Project

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#32]
The site is up and running!
Great work @abdual1100 and @James-f117 🎉 🎉 🎉

**Comment by ebeshero** [comment]
@alnopa9 @James-f117 @abdual1100 Congratulations on this gem of a project site! I have posted a detailed project evaluation in markdown here on your repo: https://github.com/alnopa9/Banksy/blob/master/banksyEvaluation_May2019.md I hope you'll keep updating your site! :-)
