### ISSUE TITLE
Website Name

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#4]
Before Dr. B creates a spot for our project's site on her server, we have to come up with a name for it. We can keep it simple and just call it Banksy. Does that work for everyone? If you have other ideas, please post them here!

**Comment by James-f117** [comment]
I'm okay with just Banksy.

**Comment by ebeshero** [comment]
So it would be http://banksy.newtfire.org 
Does that look good?

**Comment by ebeshero** [comment]
Note--That link above is leading to another site until we get yours set up. It's okay!

**Comment by alnopa9** [comment]
Just reopening this issue to bring to the team's attention that the site is now active on the server!!!
http://banksy.newtfire.org
