### ISSUE TITLE
KML

### ISSUE THREAD

**Issue by alnopa9** [alnopa9/Banksy#7]
When we eventually get everything marked up, we will need to create a map. Now, we could do this by looking at each file one at a time to get the needed information OR we could use XQuery and XSLT. We went over what XSLT does very briefly in the last team meeting, but I wanted to give you two some reading material on it. Don't forget to get your 10 XML files done for this week, too!
http://dh.obdurodon.org/kml/kml-tutorial.xhtml#xslt
http://dh.newtfire.org/XQueryExercise3.html

**Comment by ebeshero** [comment]
@alnopa9 @James-f117 @abdual1100 Hey all! The KML tutorials are good to look at, but I'm about to be updating my exercise on NewtFire! I found an easier and better way to "scrape" the geocoordinate data so my method doesn't have to be so complicated as the one I posted in that XQuery Exercise. So I'll be rewriting this to query Open Street Maps. What I learned is that Open Street Maps stores data in XML--it's actually not KML from what I can see, but it's simple and super-informative XML. I posted about this on an old project proposal here: https://github.com/ebeshero/DHClass-Hub/issues/604#issuecomment-457855402
